sut:
  build: .
  volumes:
    - ./test.sh:/test.sh
  command: sh -c "
      localstripe &
      apk update &&
      apk add bash curl wait4ports &&
      wait4ports tcp://localhost:8420 &&
      /test.sh
    "
